version: '3'
services:
 app:
   ports:
     - "10081:80"
   build: ./docker/app
   container_name: laravel_app
   volumes:
     - ./src:/var/www/html
   environment:
     - DB_CONNECTION=mysql
     - DB_HOST=db
     - DB_PORT=3306
     - DB_DATABASE=${DB_NAME:-laravel_db}
     - DB_USERNAME=${DB_USER:-laravel_user}
     - DB_PASSWORD=${DB_PASS:-laravel_pass}
  
 db:
   image: mysql:5.7
   container_name: laravel_db
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   environment:
     - DB_CONNECTION=mysql
     - DB_HOST=laravel_db
     - DB_PORT=3306
     - DB_DATABASE=${DB_NAME:-laravel_db}
     - DB_USERNAME=${DB_USER:-laravel_user}
     - DB_PASSWORD=${DB_PASS:-laravel_pass}
     
 db-test:
   image: mysql:5.7
   container_name: db-test
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./docker/db-test/data:/var/lib/mysql
     - ./docker/db-test/my.cnf:/etc/mysql/conf.d/my.cnf
   environment:
     - DB_TESTING_CONNECTION=mysql
     - DB_TESTING_HOST=laravel_db_testing
     - DB_TESTING_PORT=3000
     - DB_TESTING_DATABASE=${DB_NAME:-laravel_db_testing}
     - DB_TESTING_SERNAME=${DB_USER:-laravel_user_testing}
     - DB_PASSWORD=${DB_TESTING_PASS:-laravel_pass_testing}

 phpmyadmin1:
   image: phpmyadmin/phpmyadmin
   environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=db
     - PMA_USER=laravel_user
     - PMA_PASSWORD=laravel_pass
   links:
     - db
   ports:
      - 8083:80
   volumes:
      - /sessions

 phpmyadmin2:
   image: phpmyadmin/phpmyadmin
   environment:
     - PMA_ARBITRARY=1
     - PMA_TESTING_HOST=db-test
     - PMA_TESTING_USER=laravel_user_testing
     - PMA_TESTING_PASSWORD=laravel_pass_testing
   links:
     - db-test
   ports:
      - 8082:80
   volumes:
      - /sessions

