version: 2.1
jobs:
 build:
  docker:
   - image: circleci/php:7.4-node-browsers
  steps:
   - checkout
   - run: sudo composer self-update --1 --working-dir=./src/laravelapp
   - restore_cache:
      key: composer-v1 -{{checksum "./src/laravelapp/composer.lock"}}
   - run: composer install --working-dir=./src/laravelapp
   - save_cache:
      key: composer-v1-{{checksum "./src/laravelapp/composer.lock"}}
      paths:
       - ./src/laravelapp/vendor
   - restore_cache:
      key:npm-v1-{{checksum "./src/laravelapp/package-lock.json"}}
   - run: 
      name: npm ci 
      command: | 
       if[ !-d node_modules]; then
        npm ci
       fi
       npm ci --working-dir=./src/laravelapp
   - save_cache:
      key:npm-v1-{{checksum "./src/laravelapp/package-lock.json"}}
      paths:
       - ./src/laravelapp/node_modules
   - run:
      name: php test 
      command: cd ./src/laravelapp && touch database/laravel_db.sqlite && ./vendor/bin/phpunit