version: 2.1
jobs:
 build:
  docker:
   - image: circleci/php:7.4-node-browsers
  steps:
   - checkout
   - run: cd src/laravelapp
   - run: sudo composer self-update --1 
   - run: composer install 
   - run: npm install 
   - run:
      name: php test 
      command: ./vendor/bin/phpunit