version: 2.1
jobs:
 build:
  docker:
   - image: circleci/php:7.4-node-browsers
  steps:
   - checkout
   - run: sudo composer self-update --1 --working-dir=./src/laravelapp
   - run: composer install --working-dir=./src/laravelapp
   - run: npm install --working-dir=./src/laravelapp
   - run:
      name: php test 
      command: cd ./src/laravelapp && touch database/laravel_db.sqlite && ./vendor/bin/phpunit