version: 2.1
jobs:
 build:
  docker:
   - image: circleci/php:7.4-node-browsers
  steps:
   - checkout
   - run: woriking_directory: ./src/laravelapp
    - run: sudo composer self-update --1
    - restore_cache:
      key: composer-v1 -{{checksum "composer.lock"}}
    - run: composer install
    - save_cache:
      key: composer-v1-{{checksum "composer.lock"}}
      paths:
       -vendor
    - run: npm install
    - run:
       name: php test 
       command: cd ./src/laravelapp && touch database/laravel_db.sqlite && ./vendor/bin/phpunit